//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Hardwares = new HashSet<Hardware>();
            this.SubAreas = new HashSet<SubArea>();
        }
    
        public int AreaID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> DivisionID { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ICollection<Hardware> Hardwares { get; set; }
        public virtual ICollection<SubArea> SubAreas { get; set; }
    }
}
