//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.Areas = new HashSet<Area>();
            this.Hardwares = new HashSet<Hardware>();
        }
    
        public int DivisionID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Hardware> Hardwares { get; set; }
    }
}
