//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        public Hardware()
        {
            this.Hardware1 = new HashSet<Hardware>();
        }
    
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public int BrandID { get; set; }
        public int TypeHardwareID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> SubAreaID { get; set; }
        public string InvoiceID { get; set; }
        public string UserName { get; set; }
        public string UserNetworkName { get; set; }
        public string NameEquip { get; set; }
        public bool CriticEquip { get; set; }
        public string SerialAssigned { get; set; }
        public Nullable<System.DateTime> DateWarranty { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<Hardware> Hardware1 { get; set; }
        public virtual Hardware Hardware2 { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual TypeHardware TypeHardware { get; set; }
        public virtual Brand Brand { get; set; }
    }
}
