//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryBDMEntities : DbContext
    {
        public InventoryBDMEntities()
            : base("name=InventoryBDMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Hardware> Hardwares { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Responsable> Responsables { get; set; }
        public virtual DbSet<Software> Softwares { get; set; }
        public virtual DbSet<SubArea> SubAreas { get; set; }
        public virtual DbSet<TypeHardware> TypeHardwares { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BrandSoftware> BrandSoftwares { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
    }
}
