//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubArea
    {
        public int SubAreaID { get; set; }
        public string Name { get; set; }
        public int AreaID { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
