//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeHardware
    {
        public TypeHardware()
        {
            this.Hardwares = new HashSet<Hardware>();
        }
    
        public int TypeHardwareID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Hardware> Hardwares { get; set; }
    }
}
